### ISSUE TITLE
App Guideline - Add some info or links for further reading

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/documentation#3]
https://github.com/ScaleIT-Org/documentation/blob/master/source/appguideline.md

Concepts such as Sidecars should be linked to further reading material.

Also link the main platform documentation regarding the architecture: http://scaleit-platform-documentation.readthedocs.io/en/latest/architecture.html

**Comment by Kuhno92** [comment]
done cb95a99c2ff11c15430935b200a862053095abba
